var view = exports;
//view
view.index = function(vork){
var output = [];

output.push('');
output.push('<div id="app">');
output.push('<div id="connect">');
output.push('<form action="#">');
output.push('<fieldset> ');
output.push('<p>');
output.push('YAY!This is a chat room. Both the client-side and server-side arewritten in javascript. The source code is<a href="http://github.com/ry/node_chat/tree/master">here</a>.');
output.push('</p>');
output.push('<label for="nick">Name</label>');
output.push('<input id="nickInput" class="text"type="text" name="nick" value=""/>');
output.push('<input id="connectButton" class="button" type="submit" name="" value="Join"/>');
output.push('</fieldset>');
output.push('</form>');
output.push('</div>');
output.push('<div id="loading"><p>loading</p></div>');
output.push('<div id="log">');
output.push('<table class="message"><tr><td class="date">18:58</td><td valign="top" class="nick">TTilus</td>');
output.push('<td class="msg-text">x6a616e: i think you can, there was some weird #send trick to do that</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">18:58</td><td valign="top" class="nick">TTilus</td>');
output.push('<td class="msg-text">(or i could just be terribly wrong)</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:02</td><td valign="top" class="nick">x6a616e</td>');
output.push('<td class="msg-text">TTilus: with #send you can invoke private methods</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:03</td><td valign="top" class="nick">x6a616e</td>');
output.push('<td class="msg-text">dunno how to leverage it to access instance var :-/</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:05</td><td valign="top" class="nick">x6a616e</td>');
output.push('<td class="msg-text">i3d: usually I use rspec::mocks</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:05</td><td valign="top" class="nick">dlisboa</td>');
output.push('<td class="msg-text">x6a616e: #instance_variable_get ?</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:06</td><td valign="top" class="nick">x6a616e</td>');
output.push('<td class="msg-text">dlisboa: phew I forgot that ..</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:19</td><td valign="top" class="nick">UrbanVegan</td>');
output.push('<td class="msg-text">How can I use "%" in a string as just another character (meaning "percent")?</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:20</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">"%"</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:20</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">:)</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:20</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">no need to escape it</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:20</td><td valign="top" class="nick">dominikh</td>');
output.push('<td class="msg-text">%%</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">dominikh</td>');
output.push('<td class="msg-text">ddfreyne: if you use something like "%string" % 1</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">dominikh</td>');
output.push('<td class="msg-text">eh</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">dominikh</td>');
output.push('<td class="msg-text">you get the idea</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">"foo %s bar" % [ \'hello\' ] # =&gt; "foo hello bar"</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">dominikh</td>');
output.push('<td class="msg-text">lets assume he has some other % stuff he wants to be replaced</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">"foo %% %s bar" % [ \'hello\' ] # =&gt; "foo % hello bar"</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">19:21</td><td valign="top" class="nick">dominikh</td>');
output.push('<td class="msg-text">and some he doesnt want to</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:07</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">docs should be in /usr/share, not /usr/lib/ruby/gems/1.8/doc, too</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:07</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">FHS is OS agnostic.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:08</td><td valign="top" class="nick">drbrain</td>');
output.push('<td class="msg-text">bougyman: FreeBSD doesn\'t follow the FHS</td>');
output.push('</tr></table>');
output.push('<table class="mevssage"><tr><td class="date">20:08</td><td valign="top" class="nick">drbrain</td>');
output.push('<td class="msg-text">Apple doesn\'t follow the FHS, and windows doesn\'t follow the FHS</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:08</td><td valign="top" class="nick">drbrain</td>');
output.push('<td class="msg-text">I really don\'t care about people who say "you don\'t X, Y or Z!" and won\'t pony up patches</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:11</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">the fbsd list seems split over FHS compliance</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:11</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">some of em want it, some give it the finger.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:11</td><td valign="top" class="nick">drbrain</td>');
output.push('<td class="msg-text">that\'s because they already have the heir man page</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:12</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">looks like they gave in on mounts to FHS 2.2 (freebsd did)</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:12</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">winFS was said to be FHS compliant.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:12</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">maybe we\'ll see that in the next MS product.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:13</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">it was supposed to be in Vista, but got scrapped.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:13</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">stuff in /bin should have config stuff in /etc, stuff in /usr/bin should have their configs in/usr/etc, ... IMO</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:13</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">stuff in ~/bin should have their configs in ~/etc</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:13</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">that would make a lot more sense than it does now</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:13</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">... what kind of names are "etc" and "var" anyway?</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:13</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">"config" and "data" would have made more sense</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:14</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">they make sense to me.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:14</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">even \'etc\'? etcetera? "all the rest of the stuff goes here"?</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:14</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">etc. and variable are how I read them.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:14</td><td valign="top" class="nick">catalystmediastu</td>');
output.push('<td class="msg-text">Does anyone know of a gem or Rails plugin that converts rtf documents to HTML? I\'ve </td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:15</td><td valign="top" class="nick">wmoxam</td>');
output.push('<td class="msg-text">catalystmediastu: I doubt it, you\'ll probably have to find a tool that does it, and call the tool</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:15</td><td valign="top" class="nick">ddfreyne</td>');
output.push('<td class="msg-text">bougyman: you can\'t really say that \'etc\' is a better name than \'config\'</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:16</td><td valign="top" class="nick">catalystmediastu</td>');
output.push('<td class="msg-text">wmoxam: I\'ll start looking for a generic tool for linux then. Thanks!</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:16</td><td valign="top" class="nick">wmoxam</td>');
output.push('<td class="msg-text">catalystmediastu: http://sourceforge.net/projects/rtf2html/  &lt;-- might work</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:17</td><td valign="top" class="nick">catalystmediastu</td>');
output.push('<td class="msg-text">wmoxam: Ahh that looks like it might. Thank you!</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:17</td><td valign="top" class="nick">wmoxam</td>');
output.push('<td class="msg-text">np</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:17</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">catalystmediastu: unrtf works well for that.</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:17</td><td valign="top" class="nick">bougyman</td>');
output.push('<td class="msg-text">http://www.gnu.org/software/unrtf/unrtf.html</td>');
output.push('</tr></table>');
output.push('<table class="message"><tr><td class="date">20:20</td><td valign="top" class="nick">catalystmediastu</td>');
output.push('<td class="msg-text">bougyman: Thanks, that looks like a good tool too. I\'ll look into them both a little more.</td>');
output.push('</tr></table>');
output.push('</div>');
output.push('<div id="toolbar">');
output.push('<ul id="status">');
output.push('<li><a id="usersLink" href="#">5 users</a></li>');
output.push('<li>uptime: <span id="uptime">?</span></li>');
output.push('<li>memory: <span id="rss">?</span>mb RSS</li>');
output.push('</ul>');
output.push('<input tabindex="1" type="text" id="entry"/>');
output.push('</div>');
      var html = vork.get.helper('html');
    return output.join(html.eol());
};